// Generated by CoffeeScript 2.3.0
(function() {
  $(document).ready = function() {
    console.log("TEST");
    hljs.registerLanguage('xml', require('./languages/xml'));
    return $('code').each = function(i, block) {
      console.log(block);
      return hljs.highlightBlock(block);
    };
  };

}).call(this);
